### ISSUE TITLE
Dynamic Fullbright not working correctly since Sodium 0.5.x

### ISSUE THREAD

**Issue by RisPNG** [Provismet/Dynamic-Fullbright#4]
### Type of Error

Incorrect Behaviour

### Description

As mentioned by LambdAurora in [this issue](https://github.com/CaffeineMC/sodium-fabric/issues/1968),
Sodium 0.5.x changes some things regarding the lighting stuff in the API so the injection point has changed slightly.

I also provided the video in the mentioned issue report. Entities lit up correctly, but light level as a whole don't work properly.

### Mod Version

1.1.1

### Minecraft Version

1.20.1

### Mod Loader

Quilt 0.19.2

**Comment by Provismet** [comment]
Dynamic Fullbright was never actually built against Sodium, it was always built against vanilla Minecraft with the hope that it worked alongside Sodium. So if Sodium has made a breaking change, then I likely have to use a Sodium injection point instead of a Minecraft injection point.

Unfortunately I have no familiarity with how Sodium or its injection points function. But (obviously) compatibility with Sodium is extremely important, so while this will be fixed in the next release, it will probably take a while.

If (and this is quite likely) LambDynamicLights fixes the Sodium compatibility issue on their end first, then I should be able to fix things on my end soon after (by just looking at how they fixed it).

**Comment by Provismet** [comment]
Until then though, I would recommend simply using an older Sodium version.

**Comment by RisPNG** [comment]
> Dynamic Fullbright was never actually built against Sodium, it was always built against vanilla Minecraft with the hope that it worked alongside Sodium. So if Sodium has made a breaking change, then I likely have to use a Sodium injection point instead of a Minecraft injection point.
> 
> Unfortunately I have no familiarity with how Sodium or its injection points function. But (obviously) compatibility with Sodium is extremely important, so while this will be fixed in the next release, it will probably take a while.
> 
> If (and this is quite likely) LambDynamicLights fixes the Sodium compatibility issue on their end first, then I should be able to fix things on my end soon after (by just looking at how they fixed it).

Thank you for the feedback. Looking forward to it!
